version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      # Prefix all commit messages with "fix"
      prefix: "fix"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
